import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "../lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SOUHAIL PORTFOLIO",
  icons: "/LOGO-SOUHAIL.png",
  description: "Generated by create next and bulid by souhail",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true} className="scroll-smooth">
    
      <body
        className={cn( "overflow-x-hidden antialiased ",  inter.className )} >
          <main className="w-screen h-screen -z-50">
            {children}
          </main>
      </body>
    </html>
  );
}
